In [2]:
import numpy as np
import remove_duplicates as rd

# for auto-reloading extenrnal modules
%load_ext autoreload
%autoreload 2

In [13]:
file = open('output_from_hpc_pt85\waldo.txt', 'r') 

# read dets
lines = file.readlines()
splitlines = [x.strip().split(' ') for x in lines]
image_ids = [x[0] for x in splitlines]
confidence = np.array([float(x[1]) for x in splitlines])
BB = np.array([[float(z) for z in x[2:]] for x in splitlines])

print('original length = ' + str(len(BB)))
print(BB)

input_array = np.array([[float(z) for z in x[:]] for x in splitlines])
pruned = rd.remove_duplicates(input_array)

print('new length = ' + str(pruned.shape[0]))
print(pruned)

original length = 206
[[ 288.8  425.4  317.8  479.8]
 [ 288.6  425.4  317.5  479.5]
 [ 288.9  425.5  317.5  479.5]
 [ 288.4  425.7  317.1  478.7]
 [1876.9  654.9 2303.2 1076.4]
 [1892.1  647.2 2308.4 1070. ]
 [2448.2 3935.3 2790.5 4672.3]
 [2445.7 3936.9 2790.1 4669.8]
 [2449.5 3932.2 2791.5 4670.1]
 [1897.2  650.  2282.2 1055. ]
 [1895.7  641.1 2286.6 1052.8]
 [1894.6  648.2 2282.3 1059.2]
 [1903.4  645.5 2275.7 1050.1]
 [1902.1  631.7 2310.2 1089.6]
 [1928.   626.4 2320.2 1085.7]
 [1927.   611.4 2336.9 1079.6]
 [2475.2 3960.5 2757.4 4624.4]
 [2478.7 3961.7 2761.4 4627.2]
 [1874.5  648.3 2345.1 1061.2]
 [1869.9  648.9 2339.5 1061.9]
 [1875.5  648.2 2347.9 1066.9]
 [1853.2  624.  2315.2 1091.8]
 [1865.   624.9 2320.1 1088.9]
 [1923.2  656.  2309.4 1071.1]
 [1922.2  655.7 2310.7 1070.3]
 [1923.8  656.6 2308.8 1071.8]
 [1926.4  654.6 2313.1 1054.6]
 [ 607.1  464.   874.5  737.9]
 [ 609.6  467.   881.4  751.5]
 [ 607.6  480.8  876.3  743.5]
 [ 595.8  459.4  875.6  746.7]
 [ 598.2  460.1  

In [ ]:
# output_file = open('output_from_hpc_pt85\pruned\waldo.txt', 'w') 
